name: finance_manager
description: A personal finance management app.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  # База данных
  drift: ^2.14.0
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.1.0
  path: ^1.8.3
  
  # Управление состоянием
  flutter_riverpod: ^2.4.0
  
  # Графики
  fl_chart: ^0.66.0
  
  # Форматирование
  intl: ^0.19.0
  
  # Утилиты
  shared_preferences: ^2.2.0
  uuid: ^4.0.0
  
  # Уведомления
  flutter_local_notifications: ^16.3.0
  
  # Файлы и шаринг
  file_picker: ^6.1.1
  share_plus: ^7.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  drift_dev: ^2.14.0
  build_runner: ^2.4.0
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  generate: true
  
  assets:
    - assets/images/
    - assets/icons/ 